name: "Batmon"
description: "Monitor various BMS over bluetooth"
url: https://github.com/fl4p/batmon-ha
version: "0.0.71"
slug: "batmon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_dbus: true
apparmor: true
services:
  - mqtt:need
options:
  devices:
    - address: D6:6C:0A:61:14:30
      type: sok
      alias: battery1
  mqtt_user: ""
  mqtt_password: ""
  mqtt_broker: "core-mosquitto"
  concurrent_sampling: false
  keep_alive: true
  verbose_log: false
  sample_period: 1.0
  publish_period: 2.0
  invert_current: true
  watchdog: true
  expire_values_after: 20
  install_newer_bleak: false
  bt_power_cycle: false

schema:
  devices:
    - address: str
      type: str
      alias: "str?"
      debug: "bool?"
      pin: "str?"
      algorithm: "str?"
      current_calibration: "float?"

  mqtt_user: "str?"
  mqtt_password: "str?"
  mqtt_broker: "str"
  mqtt_port: "int(1,65535)?"

  concurrent_sampling: "bool"
  invert_current: "bool"
  keep_alive: "bool"
  watchdog: "bool"

  sample_period: "float"
  publish_period: "float?"
  expire_values_after: "float"

  verbose_log: "bool"

  bt_power_cycle: "bool?"
  install_newer_bleak: "bool?"

  influxdb_host: "str?"
  influxdb_username: "str?"
  influxdb_password: "str?"
  influxdb_ssl: "bool?"
  influxdb_database: "str?"